packages:
  - '.'

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true

overrides:
  react: 18.3.1
  react-dom: 18.3.1
  vite: 6.3.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
